export const config = {
  APP_VERSION: '1.0.0',
  MIN_TOPICS_REQUIRED: 3,
  MAX_FEEDBACK_HISTORY: 500,
  RERANK_AFTER_SIGNALS: 3,
  DEFAULT_MORNING_START_HOUR: 7,
  DEFAULT_MORNING_END_HOUR: 9,
  MAX_FEED_ITEMS: 50,
};
